apiVersion: v1
kind: ConfigMap
metadata:
  name: appa-runtime-policy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "appa-demo.labels" . | nindent 4 }}
data:
  demo.appa.toml: |
{{ include "appa-demo.policy" . | indent 4 }}
