{{- if and .Values.openai.apiKey (not .Values.openai.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.modelConfig.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appa-demo.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.openai.apiKey | quote }}
{{- end }}
