#!/usr/bin/env python3
"""Derive the beat grid of the OpenAPPA song for the dancing header mascot.

Writes website/lib/song-beats.ts from website/public/brand/openappa-check-the-flow.mp3.
Rerun when the recording changes. Needs ffmpeg on PATH and numpy.

Method: decode to 22.05 kHz mono; onset strength = half-wave-rectified
log-spectral flux (full band mixed 50/50 with a 30-180 Hz bass band, so the
kick anchors the grid); dynamic-programming beat tracking (Ellis 2007) seeded
at 125 BPM; each beat smoothed by a local linear fit over its 12 neighbours;
per-bar intensity = bar RMS mapped linearly from 0.06 to 0.20 onto 0..1.
The song's tempo drifts (about 125.4 BPM before 65 s, 124.9 after), so the
beats are stored as timestamps, not as one BPM.
"""

import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
MP3 = ROOT / "website/public/brand/openappa-check-the-flow.mp3"
OUT = ROOT / "website/lib/song-beats.ts"

SR = 22050
N_FFT = 1024
HOP = 64
FPS = SR / HOP
SEED_BPM = 125.0
BEATS_PER_BAR = 4
RMS_LO, RMS_HI = 0.06, 0.20


def decode(path: Path) -> np.ndarray:
    raw = subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-i", str(path), "-vn", "-ac", "1", "-ar", str(SR), "-f", "f32le", "-"],
        check=True,
        capture_output=True,
    ).stdout
    return np.frombuffer(raw, dtype=np.float32)


def onset_strength(y: np.ndarray) -> np.ndarray:
    win = np.hanning(N_FFT)
    frames = (len(y) - N_FFT) // HOP
    freqs = np.fft.rfftfreq(N_FFT, 1 / SR)
    bass = (freqs >= 30) & (freqs <= 180)
    full = np.zeros(frames)
    low = np.zeros(frames)
    prev = None
    for i in range(frames):
        mag = np.log1p(1000 * np.abs(np.fft.rfft(y[i * HOP : i * HOP + N_FFT] * win)))
        if prev is not None:
            d = mag - prev
            d[d < 0] = 0
            full[i] = d.sum()
            low[i] = d[bass].sum()
        prev = mag

    def norm(o: np.ndarray) -> np.ndarray:
        k = int(FPS * 0.3)
        o = o - np.convolve(o, np.ones(k) / k, mode="same")
        o[o < 0] = 0
        return o / o.max()

    return 0.5 * norm(full) + 0.5 * norm(low)


def track_beats(onset: np.ndarray, bpm: float, tightness: float = 600) -> np.ndarray:
    period = 60 * FPS / bpm
    n = len(onset)
    score = np.full(n, -1e9)
    back = np.full(n, -1, dtype=int)
    window = np.arange(-int(2 * period), -int(period / 2) + 1)
    penalty = -tightness * (np.log(-window / period)) ** 2
    for i in range(n):
        if i < int(period / 2):
            score[i] = onset[i]
            continue
        cand = i + window
        ok = cand >= 0
        s = score[cand[ok]] + penalty[ok]
        k = np.argmax(s)
        score[i] = onset[i] + s[k]
        back[i] = cand[ok][k]
    i = np.argmax(score[-int(period) :]) + n - int(period)
    beats = []
    while i >= 0:
        beats.append(i)
        i = back[i]
    return np.array(beats[::-1]) * HOP / SR


def smooth(beats: np.ndarray) -> np.ndarray:
    out = np.empty_like(beats)
    for i in range(len(beats)):
        lo, hi = max(0, i - 6), min(len(beats), i + 7)
        k = np.arange(lo, hi)
        slope, icpt = np.polyfit(k, beats[lo:hi], 1)
        out[i] = slope * i + icpt
    return out


def bar_intensity(y: np.ndarray, beats: np.ndarray) -> np.ndarray:
    rms = []
    for i in range(0, len(beats), BEATS_PER_BAR):
        s0 = int(beats[i] * SR)
        s1 = int(beats[i + BEATS_PER_BAR] * SR) if i + BEATS_PER_BAR < len(beats) else len(y)
        rms.append(np.sqrt(np.mean(y[s0:s1] ** 2)) if s1 > s0 else 0.0)
    raw = np.clip((np.array(rms) - RMS_LO) / (RMS_HI - RMS_LO), 0, 1)
    out = raw.copy()
    for i in range(1, len(raw) - 1):
        out[i] = 0.5 * np.median(raw[i - 1 : i + 2]) + 0.5 * raw[i]
    return out


def main() -> None:
    y = decode(MP3)
    beats = smooth(track_beats(onset_strength(y), SEED_BPM))
    intensity = bar_intensity(y, beats)
    ms = np.round(beats * 1000).astype(int)
    ivals = np.diff(beats) * 1000
    print(f"{len(ms)} beats, {60000 / ivals.mean():.2f} BPM mean, intervals {ivals.min():.0f}-{ivals.max():.0f} ms", file=sys.stderr)

    def rows(items: list[str], per_row: int) -> str:
        return "\n".join("  " + ", ".join(items[i : i + per_row]) + "," for i in range(0, len(items), per_row))

    OUT.write_text(
        "// Generated by scripts/appa-song-beats.py from\n"
        "// public/brand/openappa-check-the-flow.mp3. Do not edit by hand.\n"
        "\n"
        "/** Beat onsets of the OpenAPPA song, in ms from the start of the clip. */\n"
        "export const SONG_BEATS_MS: readonly number[] = [\n"
        f"{rows([str(v) for v in ms], 12)}\n"
        "];\n"
        "\n"
        f"export const SONG_BEATS_PER_BAR = {BEATS_PER_BAR};\n"
        "\n"
        "/** Loudness of each bar, 0 (silence) to 1 (full chorus). */\n"
        "export const SONG_BAR_INTENSITY: readonly number[] = [\n"
        f"{rows([f'{v:.2f}' for v in intensity], 12)}\n"
        "];\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
