//! Repository tooling: render a catalog from a clean snapshot of its packages.
use std::collections::BTreeMap;
use std::path::Path;

use appa_package::{MANIFEST_FILE, Package, Role, SCHEMA, TreeDigest, check_ownership, validate_package};
use serde::Serialize;

#[derive(Serialize)]
struct Catalog {
    schema: u32,
    name: &'static str,
    packages: BTreeMap<&'static str, BTreeMap<String, Entry>>,
}

#[derive(Serialize)]
struct Entry {
    path: String,
    digest: String,
}

fn render(root: &Path) -> Result<String, String> {
    let mut catalog = Catalog {
        schema: SCHEMA,
        name: "appa",
        packages: BTreeMap::new(),
    };
    let mut packages: Vec<Package> = Vec::new();
    for (directory, kind) in [("plugins", "plugin"), ("batteries", "battery")] {
        for entry in std::fs::read_dir(root.join(directory)).map_err(|error| error.to_string())? {
            let path = entry.map_err(|error| error.to_string())?.path();
            if !path.join(MANIFEST_FILE).exists() {
                continue;
            }
            let package = validate_package(&path).map_err(|error| error.to_string())?;
            let actual = match &package.role {
                Role::Plugin(_) => "plugin",
                Role::Battery(_) => "battery",
            };
            if actual != kind || path.file_name().and_then(|name| name.to_str()) != Some(package.name.as_str()) {
                return Err(format!(
                    "{} must be a {kind} package named after its directory",
                    path.display()
                ));
            }
            let entry = Entry {
                path: format!("{directory}/{}", package.name),
                digest: TreeDigest::of_tree(&path)
                    .map_err(|error| error.to_string())?
                    .to_string(),
            };
            catalog
                .packages
                .entry(kind)
                .or_default()
                .insert(package.name.to_string(), entry);
            packages.push(package);
        }
    }
    check_ownership(&packages).map_err(|error| error.to_string())?;
    let body = toml::to_string_pretty(&catalog).map_err(|error| error.to_string())?;
    Ok(format!(
        "# Generated by scripts/appa-marketplace.sh. Do not edit by hand.\n{body}"
    ))
}

fn main() {
    let args: Vec<_> = std::env::args_os().skip(1).collect();
    if args.len() != 1 {
        eprintln!("usage: marketplace <clean-marketplace-directory>");
        std::process::exit(2);
    }
    match render(Path::new(&args[0])) {
        Ok(catalog) => print!("{catalog}"),
        Err(error) => {
            eprintln!("{error}");
            std::process::exit(1);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use appa_package::Marketplace;

    fn battery(root: &Path, directory: &str, name: &str) {
        let path = root.join("batteries").join(directory);
        std::fs::create_dir_all(&path).unwrap();
        std::fs::write(
            path.join(MANIFEST_FILE),
            format!("schema = 1\nname = {name:?}\ndescription = \"test\"\n[battery]\npolicy = \"appa.toml\"\nhosts = [\"kagent\"]\n"),
        ).unwrap();
        std::fs::write(path.join("appa.toml"), "[policy]\nversion = 2\n").unwrap();
    }

    #[test]
    fn discovers_packages_and_updates_digests_without_an_existing_catalog() {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir(root.path().join("plugins")).unwrap();
        battery(root.path(), "slack", "slack");
        battery(root.path(), "github", "github");
        let first = render(root.path()).unwrap();
        assert_eq!(first, render(root.path()).unwrap());
        let parsed = Marketplace::parse(&first, Path::new("marketplace.toml")).unwrap();
        assert_eq!(
            parsed.packages.iter().map(|p| p.name.as_str()).collect::<Vec<_>>(),
            ["github", "slack"]
        );

        std::fs::write(root.path().join("batteries/github/README.md"), "new package content").unwrap();
        let updated = Marketplace::parse(&render(root.path()).unwrap(), Path::new("marketplace.toml")).unwrap();
        assert_ne!(parsed.packages[0].digest, updated.packages[0].digest);
        assert_eq!(parsed.packages[1].digest, updated.packages[1].digest);
    }

    #[test]
    fn refuses_a_directory_with_a_different_package_identity() {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir(root.path().join("plugins")).unwrap();
        battery(root.path(), "github", "slack");
        assert!(render(root.path()).unwrap_err().contains("named after its directory"));
    }
}
